### ISSUE TITLE
Prevent keyboard popup in mobile

### ISSUE THREAD

**Issue by watoo** [ondras/my-mind#106]
When we open my-mind in mobile phone, keyboard popups every time when the port area is clicked. I tried using the blur() function but it doesn't work, here is my code:

```
MM.Map.prototype.getItemFor = function (node) {
    if (isReadOnly) {
        blur();
    }
    var port = this._root.getDOM().node.parentNode;
```
How can we prevent this keyboard popup?

**Comment by ondras** [comment]
I believe this is because of `MM.Clipboard`, the object that maintains a hidden `<textarea>` with the currently selected node's serialized contents so that you can do Ctrl+C.

You may try commenting out its `focus()` method (https://github.com/ondras/my-mind/blob/3a4c0d93fc53a41d2135babfbb1ca11f3270a7bf/src/clipboard.js#L18) to see if that is the reason for keyboard popup.

Generally speaking, the clipboard handling code can be probably improved (e.g. removing the need for a permanently focused hidden textarea), because browsers allow Clipboard access in a more modern fashion these days.
