### ISSUE TITLE
Export picture error

### ISSUE THREAD

**Issue by tk-zc** [ondras/my-mind#90]
When a mind map exports a picture, image. PHP outputs the error message` Error call PhantomJS, return code 1`. How to do this?

**Comment by ondras** [comment]
Hi @tk-zc, thanks for the bugreport.

The My Mind app itself is not able to export images, so we were using a hack here: in order to export an image, we simply called a remote server service to do a *screenshot* of the map inside of an invisible headless browser (running on said server).

The server we used is apparently no longer working. This is not a fault of the My Mind app itself and cannot be really fixed by pushing code changes. We need to find another hosted server service that could do these screenshots for us.

**Comment by tk-zc** [comment]
> Hi @tk-zc, thanks for the bugreport.
> 
> The My Mind app itself is not able to export images, so we were using a hack here: in order to export an image, we simply called a remote server service to do a _screenshot_ of the map inside of an invisible headless browser (running on said server).
> 
> The server we used is apparently no longer working. This is not a fault of the My Mind app itself and cannot be really fixed by pushing code changes. We need to find another hosted server service that could do these screenshots for us.

Hi @ondras ,Now that the problem of exporting pictures has been solved, I can run `phantomjs phantomjs-my-mind.js URL output.png` from the local command line to export pictures. Thank you very much for your help.

eg: `phantomjs phantomjs-my-mind.js http://127.0.0.1/tools/my-mind-master/index.html?Url=http%3A%2F%2F127.0.0.1%2Ftools%2Fmy-mind-master%2Fexamples%2FGoldfish.my output.png`

**Comment by ondras** [comment]
Might be relevant: https://github.com/ondras/my-mind/wiki/Saving-images-client-side

**Comment by ondras** [comment]
Exporting images should work once again! See #134 for more info.
